# The open source Nylas Mail Client for Linux and Mac. See AppVeyor for
# Windows
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

branches:
  only:
  - master
  - /ci-.*/
  - /stable.*/

matrix:
  include:
  - os: linux
    env: NODE_VERSION=6.9 CC=gcc-4.8 CXX=g++-4.8
  - os: osx
    env: NODE_VERSION=6.9 CC=clang CXX=clang++ APPLE_CODESIGN_KEY_PASSWORD=""

install:
- git clone https://github.com/creationix/nvm.git /tmp/.nvm
- source /tmp/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION

before_script:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
  export DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start;
  fi

script:
- npm install && npm test

cache:
  directories:
    - node_modules
    - apm/node_modules
